language: csharp
solution: NeverBounceSDK.sln
install:
  - nuget restore NeverBounceSDK.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release NeverBounceSDK.sln
  - mono testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./NeverBounceSDKTests/bin/Release/NeverBounceSDKTests.dll
